# Generated by Django 3.0.5 on 2020-06-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('sistema_operativo', models.CharField(db_column='sistema_operativo', max_length=100)),
                ('nombre', models.CharField(db_column='nombre', max_length=30)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('tipo', models.CharField(choices=[('C', 'Cliente'), ('S', 'Servidor')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maquinas',
            },
        ),
        migrations.CreateModel(
            name='UsuarioMaquina',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('usuario', models.CharField(db_column='usuario', max_length=50)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maquina', models.ForeignKey(db_column='maquina_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app.Maquina')),
            ],
            options={
                'db_table': 'usuario_maquinas',
            },
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('modo', models.CharField(db_column='modo', max_length=100, null=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('version', models.CharField(db_column='version', max_length=10)),
                ('root_path', models.CharField(db_column='root', max_length=255, null=True)),
                ('puerto_admin', models.IntegerField(db_column='puerto_admin', null=True)),
                ('usuario_admin', models.CharField(db_column='usuario_admin', max_length=50, null=True)),
                ('password_admin', models.CharField(db_column='password_admin', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(db_column='maquina_id', on_delete=django.db.models.deletion.CASCADE, related_name='servidores', to='app.Maquina')),
            ],
            options={
                'db_table': 'servidores',
            },
        ),
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('ip', models.CharField(db_column='ip', max_length=15)),
                ('interfaz', models.CharField(db_column='interfaz', max_length=10, null=True)),
                ('mac', models.CharField(db_column='mac_address', max_length=100)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maquina', models.ForeignKey(db_column='maquina_id', on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='app.Maquina')),
            ],
            options={
                'db_table': 'ips',
            },
        ),
        migrations.CreateModel(
            name='HostVirtual',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', default='0.0.0.0', max_length=100, null='False')),
                ('puerto', models.IntegerField(db_column='puerto', default=80)),
                ('default', models.BooleanField(db_column='default', default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(db_column='servidor_id', on_delete=django.db.models.deletion.CASCADE, related_name='host_virtuales', to='app.Servidor')),
            ],
            options={
                'db_table': 'host_virtuales',
            },
        ),
        migrations.CreateModel(
            name='Aplicacion',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('ruta_web', models.CharField(db_column='ruta_web', max_length=100)),
                ('version', models.CharField(db_column='version', max_length=10, null=True)),
                ('repositorio', models.CharField(db_column='repositorio', max_length=255, null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('host_virtual', models.ForeignKey(db_column='host_virtual_id', on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='app.HostVirtual')),
            ],
            options={
                'db_table': 'aplicaciones',
            },
        ),
    ]
