# Generated by Django 3.0.5 on 2020-06-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='valido',
            field=models.BooleanField(db_column='valido', default=True),
        ),
    ]
