# Generated by Django 3.0.5 on 2020-06-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_servidor_valido'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostvirtual',
            name='activo',
            field=models.BooleanField(db_column='activo', default=True),
        ),
    ]
